using System;
using System.Security.Claims;
using AspNet.Security.OpenIdConnect.Primitives;
using Microsoft.AspNetCore.Mvc;
using PsychedelicExperience.Common;
using PsychedelicExperience.Membership.Messages.Users;

namespace PsychedelicExperience.Web.Controllers.Api
{
    public static class ClaimsPrincipalExtensions
    {
        public static UserId GetUserId(this ClaimsPrincipal principal)
        {
            if (principal == null || !principal.Identity.IsAuthenticated) return null;

            var id = principal.FindFirstValue(OpenIdConnectConstants.Claims.Subject);
            return Guid.TryParse(id, out var guid) ? new UserId(guid) : null;
        }

        public static UserId GetAuthorizedUserId(this ClaimsPrincipal principal)
        {
            var id = principal.GetUserId();
            if (id == null)
            {
                throw new InvalidOperationException("Could not get userid.");
            }
            return id;
        }
    }

    public static class IdExtensions
    {
        public static IActionResult AcceptedWhenRecent(this Id id)
        {
            //How to cope with eventual consistency of the projections:
            //Here we assume that a created resource with an ID generated in the last 60 seconds
            //is still being generated by the async projections.
            //When the client receives a 202 it should retry the API call until a 200 or a 
            //404 is found.
            var timestamp = id.GetTimestamp();
            var difference = Math.Abs(timestamp.Subtract(DateTimeOffset.UtcNow).TotalSeconds);

            return difference > 60 ? new NotFoundResult() : new StatusCodeResult(202);
        }
    }
}